version: '3.8'

services:
  # -------------------------------------------------------------------
  # FastAPI Services (Maintained here for easy local image building)
  # -------------------------------------------------------------------
  api-gateway:
    build: 
      context: ./gateway
    image: ai_platform_kubernetes-api-gateway:latest # Sets the exact name Kubernetes expects
    container_name: api_gateway
    ports:
      - "3000:3000"

  router-service:
    build: 
      context: ./router
    image: ai_platform_kubernetes-router-service:latest # Sets the exact name Kubernetes expects
    container_name: router_service
    ports:
      - "3001:3000"

  llm-proxy:
    build: 
      context: ./proxy
    image: ai_platform_kubernetes-llm-proxy:latest # Sets the exact name Kubernetes expects
    container_name: llm_proxy
    ports:
      - "3002:3000"