apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway 
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.port }}
      targetPort:  {{ .Values.gateway.port }}