apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: {{ .Values.proxy.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.proxy.port }}
        env:
        - name: REDIS_URL
          value: "redis://my-redis-master:6379/0" # Points to the Bitnami Redis we just deployed
        - name: ROUTER_URL
          value: "http://router-service:3000"